import Head from "next/head";
import { Card } from "../../components/Card";
import { Footer } from "../../components/Footer";
import { Header } from "../../components/Header";
import fs from "fs";
import matter from "gray-matter";
import { Pagination } from "../../components/Pagination";

type PageProps = {
  posts: {
    slug: string;
    data: {
      [key: string]: any;
    };
  }[];
};

type PathParams = {
  params: {
    page: number;
  };
};

const PAGE_SIZE = 2;

const range = (start: number, end: number) =>
  [...Array(end - start + 1)].map((_, i) => start + i);

export const getStaticPaths = async () => {
  const files = fs.readdirSync("posts");
  const count = files.length;

  const paths = range(1, Math.ceil(count / PAGE_SIZE)).map((i) => ({
    params: { page: i.toString() },
  }));

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = (paths: PathParams) => {
  const current_page = paths.params.page;
  console.log("page", current_page);
  const files = fs.readdirSync("posts");
  const posts = ([] = files.map((fileName) => {
    const slug = fileName.replace(/\.md$/, "");
    const fileContent = fs.readFileSync(`posts/${fileName}`, "utf-8");
    const { data } = matter(fileContent);
    return { slug, data };
  }));

  const pages = range(1, Math.ceil(posts.length / PAGE_SIZE));

  const sortedPosts = posts.sort((postA, postB) =>
    new Date(postA.data.date) > new Date(postB.data.date) ? -1 : 1
  );

  const slicedPosts = sortedPosts.slice(
    PAGE_SIZE * (current_page - 1),
    PAGE_SIZE * current_page
  );

  return { props: { posts: slicedPosts, pages, current_page } };
};

const Page: React.FC<PageProps> = ({ posts }) => {
  return (
    <div>
      <Head>
        <title>人生は神ゲー</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        <div className="w-full md:w-8/12 mx-auto">
          <div>
            <h1 className="text-lg font-bold my-16 text-center">
              人生は神ゲー
            </h1>
          </div>
          {posts.map((post) => {
            return (
              <Card
                key={post.slug}
                slug={post.slug}
                title={post.data.title}
                date={post.data.date}
                description={post.data.description}
                thumbnail={post.data.thumbnail}
              />
            );
          })}
        </div>
      </main>
      <Footer />
      <Pagination totalCount={posts.length} />
    </div>
  );
};

export default Page;
