import Head from "next/head";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import Image from "next/image";
import styles from "../styles/Post.module.css";

const Home: React.FC = () => {
  return (
    <div className="w-full md:w-8/12 mx-auto text-gray-800">
      <Head>
        <title>人生は神ゲー</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        <div className="w-full md:w-8/12 mx-auto">
          <div className={styles.imageContainer}>
            <Image
              className={styles.image}
              src={"/japanese-style.jpg"}
              layout="fill"
              alt="thumbnail"
              objectFit="contain"
            ></Image>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
