import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Card } from "../components/Card";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import styles from "../styles/Home.module.css";

import fs from "fs";
import matter from "gray-matter";

type PageProps = {
  posts: {
    slug: string;
    data: {
      [key: string]: any;
    };
  }[];
};
export const getStaticProps = (): PageProps => {
  const files = fs.readdirSync("posts");
  const posts = ([] = files.map((fileName) => {
    const slug = fileName.replace(/\.md$/, "");
    const fileContent = fs.readFileSync(`posts/${fileName}`, "utf-8");
    console.log(fileContent);
    const { data } = matter(fileContent);
    return { slug, data };
  }));
  return {
    posts,
  };
};

const Home: React.FC<PageProps> = (props) => {
  return (
    <div>
      <Head>
        <title>からをやぶる</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        <div>
          <h1 className="text-lg font-bold my-16 text-center">
            東京在住フリーランスエンジニアのブログ
          </h1>
        </div>
        <Card
          title={props.posts[0].data.title}
          date={props.posts[0].data.title}
          description={props.posts[0].data.description}
        />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
