/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import { BLOG_TITLE, GITHUB_URL, TWITTER_URL } from "../lib/env";
import { ProfileImage } from "../components/ProfileImage";
import { ProfileLink } from "../components/ProfileLink";
import { getProfile } from "./api/Article";
import ReactMarkdown from "react-markdown";
import styles from "../styles/Markdown.module.css";

export const getStaticProps = () => {
  const post = getProfile();
  return { props: post };
};

type PageProps = {
  content: string;
  data: { [key: string]: string };
};

const Profile: React.FC<PageProps> = ({ content, data }) => {
  return (
    <div className="w-full md:w-8/12 mx-auto text-gray-800">
      <Head>
        <title>{`Profile | ${BLOG_TITLE}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />

      <main>
        <div className="w-full md:w-8/12 mx-auto">
          <h1 className="text-3xl font-bold mt-16 mb-4 mx-4">Profile</h1>
          <div className="w-1/3 my-12 mx-auto">
            <ProfileImage />
          </div>
          <p className="text-center text-xl mt-8 mb-4">ash</p>
          <div className="flex justify-center mb-24">
            <div className="mx-3">
              <ProfileLink url={TWITTER_URL}></ProfileLink>
            </div>
            <div className="mx-3">
              <ProfileLink url={GITHUB_URL}></ProfileLink>
            </div>
          </div>
          <div className={styles.post}>
            <ReactMarkdown>{content}</ReactMarkdown>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Profile;
