import Head from "next/head";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import Image from "next/image";
import styles from "../styles/About.module.css";
import { Logo } from "../components/Logo";
import { BLOG_TITLE } from "../lib/env";

const Home: React.FC = () => {
  return (
    <div className="w-full md:w-8/12 mx-auto text-gray-800">
      <Head>
        <title>{`Profile | ${BLOG_TITLE}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />

      <main>
        <div className="w-full md:w-8/12 mx-auto">
          <h1 className="text-3xl font-bold mt-16 mb-4">Profile</h1>
          <div className={`${styles.imageContainer} w-1/3 my-12 mx-auto`}>
            <Image
              className={`${styles.image} rounded-full`}
              src={"/logo.png"}
              layout="fill"
              alt="thumbnail"
              objectFit="contain"
            ></Image>
          </div>
          <p className="text-center text-xl mt-8 mb-4">Ash / あさひ</p>
          <div className="flex justify-center">
            <div className="mx-3">
              <a
                href="https://twitter.com/Asahishu712"
                target="_blank"
                rel="noreferrer"
              >
                <Logo logo="/twitter.svg" />
              </a>
            </div>
            <div className="mx-3">
              <a
                href="https://github.com/ShumpeiAsahi"
                target="_blank"
                rel="noreferrer"
              >
                <Logo logo="/github.svg" />
              </a>
            </div>
          </div>
          <div className="mt-16 mb-4 mx-4">
            <p>1997年生まれのエンジニア。</p>
            <br />
            <p>【経歴】</p>
            <p>
              2021年4月 新卒入社したSIerでエンジニアとしてのキャリアをスタート。
            </p>
            <p>2022年5月 フリーランスになり、ソフトウェア企業で業務委託。</p>
            <br />
            <p>【保有スキル】</p>
            <p>言語</p>
            <p>TypeScript/Next/Kotlin/Vue/Ruby on Rails/PHP/Clojure</p>
            <p>OS・インフラ</p>
            <p>Ubuntu/RedHat/Docker/AWS/GCP</p>
            <br />
            <p>人生は神ゲーだ！</p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
