name: Manually deploy to vercel
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: yarn install

      - name: Clone MarkDown Repository
        uses: actions/checkout@v3
        with:
          repository: ShumpeiAsahi/ash-blog-store
          token: ${{ secrets.GH_PAT }}
          path: posts

      - name: Check repo
        run: ls posts -a

      - name: Build
        run: yarn build

      - name: Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          vercel-args: "--prod"
          working-directory: ./
